const data =[
    {
        id:"1",
question:"How to download the app?",
answer:"Just request a free demo session to get the mobile App"
    },
    {
        id:"2",
question:"How to get the attendance marked?",
answer:" Get your attendance marked, just you need to scan the QR which is generated by the teacher ."
    },
    {
        id:"3",
question:"How to track Attendance?",
answer:"You need to open the proxyy app and you can track your attendance on daily, monthly, semester wise."
    },

    ]
export default data;